#!/bin/bash
# Sustained campaign batch runner for: {SLUG}
# Generated by /marketing sustain create
# Invoked by macOS launchd on schedule — runs Claude Code headlessly

set -euo pipefail

CAMPAIGN_DIR="{CAMPAIGN_DIR}"
STATE_FILE="$CAMPAIGN_DIR/campaign-state.json"
CONFIG_FILE="$CAMPAIGN_DIR/campaign-config.json"
LOGDIR="$CAMPAIGN_DIR/logs"

mkdir -p "$LOGDIR"

# --- Guard checks ---

STATUS=$(python3 -c "import json; print(json.load(open('$STATE_FILE'))['status'])")
CURRENT=$(python3 -c "import json; print(json.load(open('$STATE_FILE'))['current_batch'])")
TOTAL=$(python3 -c "import json; print(json.load(open('$CONFIG_FILE'))['total_batches'])")

# Skip if paused or already completed
if [ "$STATUS" != "active" ]; then
    echo "$(date -u +%FT%TZ) Campaign is $STATUS — skipping batch." >> "$LOGDIR/skipped.log"
    exit 0
fi

# Auto-complete if all batches done
if [ "$CURRENT" -ge "$TOTAL" ]; then
    echo "$(date -u +%FT%TZ) All $TOTAL batches completed. Marking campaign as completed." >> "$LOGDIR/skipped.log"
    python3 -c "
import json
with open('$STATE_FILE') as f:
    s = json.load(f)
s['status'] = 'completed'
with open('$STATE_FILE', 'w') as f:
    json.dump(s, f, indent=2)
"
    exit 0
fi

# --- Bi-weekly skip logic ---
CADENCE=$(python3 -c "import json; print(json.load(open('$CONFIG_FILE')).get('cadence', 'weekly'))")
if [ "$CADENCE" = "bi-weekly" ]; then
    CREATED=$(python3 -c "import json; print(json.load(open('$CONFIG_FILE'))['created_at'])")
    SKIP=$(python3 -c "
from datetime import datetime
created = datetime.fromisoformat('$CREATED'.replace('Z', '+00:00'))
now = datetime.now(created.tzinfo) if created.tzinfo else datetime.now()
weeks = (now - created).days // 7
print('yes' if weeks % 2 != 0 else 'no')
")
    if [ "$SKIP" = "yes" ]; then
        echo "$(date -u +%FT%TZ) Bi-weekly skip (odd week) — skipping batch." >> "$LOGDIR/skipped.log"
        exit 0
    fi
fi

# --- Execute batch ---

NEXT_BATCH=$((CURRENT + 1))
BATCH_PAD=$(printf "%03d" "$NEXT_BATCH")
LOGFILE="$LOGDIR/batch-${BATCH_PAD}.log"

echo "$(date -u +%FT%TZ) Starting batch $NEXT_BATCH/$TOTAL" >> "$LOGFILE"

# Record start time for duration tracking
START_SEC=$(date +%s)

{CLAUDE_PATH} -p \
    --dangerously-skip-permissions \
    --model opus \
    "Run sustained-campaign-batch for campaign slug '{SLUG}'. Campaign directory: $CAMPAIGN_DIR. Execute batch $NEXT_BATCH of $TOTAL. Read the following files for context: $CAMPAIGN_DIR/campaign-config.json, $CAMPAIGN_DIR/campaign-state.json, $CAMPAIGN_DIR/content-calendar.json, $CAMPAIGN_DIR/foundation/02-strategy/marketing-strategy.md. Follow the sustained-campaign-batch pipeline mode from the marketing-orchestrator instructions. Write all batch output to $CAMPAIGN_DIR/batches/batch-${BATCH_PAD}/. Update campaign-state.json, content-calendar.json, and batch-history.json when done." \
    >> "$LOGFILE" 2>&1

EXIT_CODE=$?
END_SEC=$(date +%s)
DURATION=$((END_SEC - START_SEC))

if [ $EXIT_CODE -ne 0 ]; then
    echo "$(date -u +%FT%TZ) Batch $NEXT_BATCH FAILED (exit code $EXIT_CODE, ${DURATION}s)" >> "$LOGFILE"
    # Update state with failure — don't prevent future runs
    python3 -c "
import json
from datetime import datetime
with open('$STATE_FILE') as f:
    s = json.load(f)
s['last_run_at'] = datetime.utcnow().strftime('%Y-%m-%dT%H:%M:%SZ')
s['last_run_status'] = 'failed'
s['last_run_duration_sec'] = $DURATION
with open('$STATE_FILE', 'w') as f:
    json.dump(s, f, indent=2)
"
    exit 1
fi

echo "$(date -u +%FT%TZ) Batch $NEXT_BATCH completed successfully (${DURATION}s)" >> "$LOGFILE"
